filebeat.inputs:
- type: filestream
  paths: /usr/local/app/log/eswebapp/*.log
  parsers:
    - ndjson:
        target: ""
        add_error_key: true
        overwrite_keys: true

output.logstash:
  hosts: ["localhost:5044"]
