metricbeat.modules:
 - module: prometheus
   period: 60s
   hosts: ["localhost:9090"]
   metrics_path: /actuator/prometheus

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.logstash:
  hosts: ["localhost:5044"]
